app = "web-parser"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "web_parser_data"
  destination = "/app/data"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
